using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    public GameObject ball;
    Vector3 offset; //Questa Ã¨ la distanza tra la palla e la cam
    public float lerpRate;
    public bool gameOver;

    // Start is called before the first frame update
    void Start()
    {
        //Calcolo la distanza tra la palla e la cam
        offset = ball.transform.position - transform.position;
        gameOver = false;
    }

    // Update is called once per frame
    void Update()
    {
        if(!gameOver)
        {
            Follow();
        }
    }

    void Follow()
    {
        Vector3 pos = transform.position; //Calcolo la posizione attuale della cam
        Vector3 targetPos = ball.transform.position - offset;
        pos = Vector3.Lerp(pos, targetPos, lerpRate * Time.deltaTime);
        transform.position = pos;
    }
}
